### ISSUE TITLE
Does unbound_value need to be exposed just to support pairlist creation from string tuples?

### ISSUE THREAD

**Issue by yutannihilation** [extendr/extendr#195] opened 2021-03-20 00:44 UTC
(second round of #187)

### Background

When we call a function, there's two types of cases:

1. use a fixed number of arguments that is determined on compile
2. use an arbitrary number of arguments that is determined on runtime

For case 1, we'll able to write as the following after #190.

``` r
f.call(pairlist!(a = r!(1), r(2)))
```

We can provide more sophisticated interface by using procedural macro. However, case 2 is a different problem. As the structure of the argument is determined on runtime, the macro cannot solve the problem, iiuc. If you are curious about the real use case, please refer to my experimental package: https://github.com/yutannihilation/rr4r#rr4r_replace

The problem is how to handle named and unnamed arguments transparently. The implementation in #190 solves this by treating `""` and `na_str()` as `R_UnboundValue` so that we can write:

``` rust
let pairs = vec![("a", r!(1)), (na_str(), r!(2))];
let pairlist = Pairlist::from_pairs(pairs);
f.call(pairlist.into_robj()).unwrap()
```

### Problem

While the current approach works, I'm afraid it makes the handling of symbols different from what it should be; It differs from the behaviour of usual R functions,

``` r
as.name("")
#> Error in as.name(""): attempt to use zero-length variable name
as.name(NA_character_)
#> `NA`
```

<sup>Created on 2021-03-19 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

and exposing `unbound_value()` to users might be a bit too low-level.

```
> rextendr::rust_function(r"(
+ fn as_sym(x: String) -> Robj {
+   Symbol::from_str(x.as_str()).into_robj()
+ }
+ )", patch.crates_io = list(`extendr-api` = list(git = "https://github.com/extendr/extendr", branch = "more-wrapper-tidying"))
+ )
build directory: /tmp/RtmpafHjhM/file13fe8440d442b

    Updating crates.io index
   Compiling rextendr9 v0.0.1 (/tmp/RtmpafHjhM/file13fe8440d442b)
    Finished dev [unoptimized + debuginfo] target(s) in 1.69s
✓ Writing wrappers to /tmp/RtmpafHjhM/file13fe8440d442b/target/extendr_wrappers.R.
> x <- as_sym("")
Error: attempt to bind a variable to R_UnboundValue
> as_sym("")
Error: invalid multibyte string at '<90><c0><a8>y<f4>U'
```

Can we let the construction of a pairlist just work without tweaking the symbols' interface?

### How do cpp11/Rcpp handle pairlists?

For case 1, cpp11 uses variadic template and polymorphism to treat named and unnamed argument differently. I guess the same thing can be done by procedural macro. 

* operator `()`: https://github.com/r-lib/cpp11/blob/3c65bc56250a882613ed919d271b789aad557402/inst/include/cpp11/function.hpp#L20-L54
* `named_arg`: https://github.com/r-lib/cpp11/blob/c41056b557cabd30bb2e5b901ca92a26262e7718/inst/include/cpp11/named_arg.hpp#L11-L38

For case 2, I couldn't find the interface (maybe due to my lack of C++ skill). Maybe users need to create an unnamed list and then `set_names()`? This also looks fine to me.

**Comment by clauswilke** [comment] 2021-03-20 18:11
> exposing `unbound_value()` to users might be a bit too low-level

Why? If it's the correct way of doing it, then I think we should at least provide this approach, and maybe also promote it. A macro can deal with your case 1, but case 2 may require more sophistication. I'm generally in favor of doing things right over using slight compromises or inaccuracies for apparent simplification. That almost never works out in the long run.

If R turns `NA_character_` into a name `NA` then we should do the same. If R doesn't allow empty strings as names, we can either follow this precedent and trigger an error or internally replace empty strings with unbound values when creating pairlists. In either case, there should be an interface that allows the user to explicitly specify an unbound value.

**Comment by yutannihilation** [comment] 2021-03-21 01:42
> I'm generally in favor of doing things right over using slight compromises or inaccuracies for apparent simplification.

I totally agree with you here. I'm not proposing a compromise, I'm just afraid using `unbound_value()` is not the right thing.

> If R turns `NA_character_` into a name `NA` then we should do the same.

Agreed.

> If R doesn't allow empty strings as names

I think this isn't quite right. An empty string cannot be a symbol, but it surely can be a name. As is revealed in https://github.com/extendr/extendr/pull/190#issuecomment-799852253, an empty string is actually the name of an unnamed element in lists.

``` r
l <- list(a = 1, 2, c = 3)

.Internal(inspect(l))
#> @55b3789391f8 19 VECSXP g0c3 [MARK,REF(2),ATT] (len=3, tl=0)
#>   @55b3784b0a88 14 REALSXP g0c1 [MARK,REF(3)] (len=1, tl=0) 1
#>   @55b3784b0a50 14 REALSXP g0c1 [MARK,REF(3)] (len=1, tl=0) 2
#>   @55b3784b0a18 14 REALSXP g0c1 [MARK,REF(3)] (len=1, tl=0) 3
#> ATTRIB:
#>   @55b377676f18 02 LISTSXP g0c0 [MARK,REF(1)] 
#>     TAG: @55b374e4d790 01 SYMSXP g0c0 [MARK,REF(65535),LCK,gp=0x4000] "names" (has value)
#>     @55b3789391a8 16 STRSXP g0c3 [MARK,REF(1)] (len=3, tl=0)
#>       @55b375131d58 09 CHARSXP g0c1 [MARK,REF(35),gp=0x61] [ASCII] [cached] "a"
#>       @55b374e4fe58 09 CHARSXP g0c1 [MARK,gp=0x60] [ASCII] [cached] ""
#>       @55b374e4eae0 09 CHARSXP g0c1 [MARK,REF(266),gp=0x61] [ASCII] [cached] "c"
```

Pairlist doesn't have empty string names, but, considering the fact that assigning `""` to `names()` deletes the names at the corresponding positions, I believe empty string represents the absence of name here as well.


``` r
pl <- pairlist(a = 1, 2, c = 3)

.Internal(inspect(pl))
#> @55b375098520 02 LISTSXP g0c0 [REF(2)] 
#>   TAG: @55b37520c7d0 01 SYMSXP g0c0 [MARK,REF(65535)] "a"
#>   @55b3784b0970 14 REALSXP g0c1 [MARK,REF(5)] (len=1, tl=0) 1
#>   @55b3784b0938 14 REALSXP g0c1 [MARK,REF(5)] (len=1, tl=0) 2
#>   TAG: @55b374e57e68 01 SYMSXP g0c0 [MARK,REF(1078),LCK,gp=0x6000] "c" (has value)
#>   @55b3784b0900 14 REALSXP g0c1 [MARK,REF(5)] (len=1, tl=0) 3

names(pl) <- c("", "", "c")

.Internal(inspect(pl))
#> @55b375a79ad0 02 LISTSXP g0c0 [REF(1)] 
#>   @55b3784b0970 14 REALSXP g0c1 [MARK,REF(6)] (len=1, tl=0) 1
#>   @55b3784b0938 14 REALSXP g0c1 [MARK,REF(6)] (len=1, tl=0) 2
#>   TAG: @55b374e57e68 01 SYMSXP g0c0 [MARK,REF(1083),LCK,gp=0x6000] "c" (has value)
#>   @55b3784b0900 14 REALSXP g0c1 [MARK,REF(6)] (len=1, tl=0) 3
```

**Comment by yutannihilation** [comment] 2021-03-21 01:54
This is the logic of base R behind `names<-`

``` c
	    if (STRING_ELT(val, i) != R_NilValue
		&& STRING_ELT(val, i) != R_NaString
		&& *CHAR(STRING_ELT(val, i)) != 0) /* test of length */
		SET_TAG(s, installTrChar(STRING_ELT(val, i)));
	    else
		SET_TAG(s, R_NilValue);
```

https://github.com/wch/r-source/blob/254ec9baf621de55181900067a7c89e2baa5b90a/src/main/attrib.c#L990-L1000

(`names<-` calls `do_namesgets` ([source](https://github.com/wch/r-source/blob/254ec9baf621de55181900067a7c89e2baa5b90a/src/main/names.c#L217)), and `setAttrib` is called ([source](https://github.com/wch/r-source/blob/254ec9baf621de55181900067a7c89e2baa5b90a/src/main/attrib.c#L935)), and then `namesgets` is called ([source](https://github.com/wch/r-source/blob/254ec9baf621de55181900067a7c89e2baa5b90a/src/main/attrib.c#L253-L254)))

**Comment by andy-thomason** [comment] 2021-03-30 11:40
It is clear that we need an efficient macro for `pairlist!` and i should spare some time for this
in the next few days.

**Comment by andy-thomason** [comment] 2021-04-10 12:29
This should now be better. We should now prefer to use pairlist! Reopen this if you think this is still an issue.

**Comment by yutannihilation** [comment] 2021-04-10 12:55
Thanks for improving `pairlist!` much. But, I think #203 is orthogonal to the issue I described, let me reopen.

**Comment by clauswilke** [comment] 2021-04-10 14:59
@yutannihilation Did you mean #202?

In either case, I'm confused about what exactly the issue is here. Maybe close this one and open a new one specifying any remaining things to be addressed?

**Comment by yutannihilation** [comment] 2021-04-10 15:22
Ah, yes, it was #202.

> any remaining things

I think the "Problem" I wrote in the issue description isn't changed by any of the recent pull requests. Sorry, am I misunderstanding something fundamentally...? I really don't get the context why this issue was closed.

**Comment by clauswilke** [comment] 2021-04-10 15:32
Maybe the title of the issue should be changed? If I understand correctly, it's really about named and unnamed arguments, not about how to construct a pairlist in general.

**Comment by yutannihilation** [comment] 2021-04-10 15:36
I see. The title was incorrect, sorry.

**Comment by andy-thomason** [comment] 2021-04-12 08:28
The original rationale for using unbound_value() is that to be efficient
pairlist construction should use symbols instead of strings. A pre-constructed
symbol has almost no cost compared with installing a symbol from a string
which costs tens of thousands of cycles.

This means that the `from_pairs()` constructor needs a source of symbols,
the most common case being strings, but other, more efficient options may exist
in the future.

There is no official "null" symbol as far as I know and so I picked unbound_value()
as a good alternative. Of course, as far as the users of the macro are concerned,
if they use strings they do not see this.

Likewise with the call! macro, which I plan to update.

So in essence we have two types of input to the `SymPair`
trait.

1) String-value:  `[("a", 1), ("", 2)]`
2) Symbol-value: `[(a, 1), (unbound_value(), 2)]`

Where a is a pre-defined symbol. `let a = sym!(a);`

In a loop, for example, we may choose to use 2), but for one-offs
in situations that are not performance critical we would use 1).

I am reserving the possibility of caching symbol and expression
generation so that R!, pairlist! and call! have a lower overhead.

Also note that I plan to update the call! macro so that f.call will
no longer be necessary.

**Comment by andy-thomason** [comment] 2021-04-12 08:31
If the `SymPair` trait is causing a problem, I'm happy to
reduce it to strings only.

**Comment by yutannihilation** [comment] 2021-04-12 10:25
I understand the rationale. Yet, I cannot believe it's enough to justify exposing `unbound_value()` to users. It's different from R's behavior, which I described above.

> There is no official "null" symbol as far as I know

If I understand correctly, `unbound_value()` is needed just to skip this `if` branch. We don't actually need the "official null symbol" because this is just our internal convention. So, I believe we can introduce another intermediate representation that doesn't require us to expose `unbound_value()` and achieve the efficiency at the same time.

https://github.com/extendr/extendr/blob/dc5d90106a969654f2b792b9f457e3df1d324641/extendr-api/src/wrapper/pairlist.rs#L34-L36

Anyway, I don't think this issue is very high priority. I don't want to slow you down, so you can ignore this issue for now. Just let me keep this issue open (I hope I can take care of this in future).

**Comment by andy-thomason** [comment] 2021-04-12 13:54
We could get `SymPair` to return `Option<Symbol>` for example.

**Comment by andy-thomason** [comment] 2021-04-12 13:59
We could also bypass from_pairs for the macro and build the pairlist
with a series of appending calls.

For example.

```
struct PairlistBuilder {
}

impl PairlistBuilder {
   pub fn new();
   pub fn appendNamed<S : Into<Symbol>, T: Into<Robj>>(s: S, t: T);
   pub fn appendUnnamed<T: Into<Robj>>(t: T);
   pub fn build() -> Pairlist;
}
```

Would you prefer this?

**Comment by clauswilke** [comment] 2021-06-07 18:13
Do we need to resolve this for a 0.3.0 release?

**Closed** 2021-07-19 13:26 UTC
