### ISSUE TITLE
Unable to run on Windows

### ISSUE THREAD

**Issue by CGMossa** [extendr/extendr#11] opened 2020-08-20 09:57 UTC
Currently, I am running `stable-gnu`-toolchain, with MSYS installed. 
I'm missing something, that I am not entirely sure how to configure:

```
cargo build
   Compiling libR-sys v0.1.6
error: failed to run custom build command for `libR-sys v0.1.6`

Caused by:
  process didn't exit successfully: `C:/cargo_target_dir/debug\build\libR-sys-f8980ef9d4a34bd4\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-env-changed=LIBR_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=LIBR_STATIC
  cargo:rerun-if-env-changed=LIBR_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-pc-windows-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_pc_windows_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-pc-windows-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_pc_windows_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-pc-windows-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_pc_windows_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR

  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Failure { command: "\"pkg-config\" \"--libs\" \"--cflags\" \"libR\"", output: Output { status: ExitStatus(ExitStatus(1)), stdout: "", stderr: "Package libR 
was not found in the pkg-config search path.\r\nPerhaps you should add the directory containing `libR.pc\'\r\nto the PKG_CONFIG_PATH environment variable\r\nNo package \'libR\' found\r\n" } }', C:\Users\Tyler\.cargo\registry\src\github.com-1ecc6299db9ec823\libR-sys-0.1.6\build.rs:37:51
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I tried to run `pacman -Ss r-base-dev` but that doesn't work for me.

**Comment by dasmoth** [comment] 2020-08-20 10:01
The build currently requires `pkg-config`, and that seems to be where things are failing for you.  I've not tried this under Windows, but it does appear to be possible to install pkg-config under Windows (see, _e.g._, https://stackoverflow.com/questions/1710922/how-to-install-pkg-config-in-windows), so that might be worth a try.

**Comment by CGMossa** [comment] 2020-08-20 10:07
So, this has been a blockage for me for quite a while. I think I got most of it down.
I have `pkg-config` installed. But it requires that the right library/package are installed for `pkg-config` to yield the right result. 
It says that it is looking for `libR`. I have to make sure that this is accessible, so I have to make sure it is installed. I've opened msys2 terminal and tried to just search for `libR` package, and there are too many matches.
I've opened the travis files here, and read the packages in them, but none point to the libR stuff. 

I think `libR` is like `RMath` stuff that you only get when you are able to build R directly. Then one can supply parameters that makes R-build spit them out as well. 

But you guys are doing it somehow through just installing them from somewhere. I "just" need to know that. 

I am also seeing a bunch of environment variables that are set in RStudio session, but not by default on Windows. I'll make a list of them here. 

I would wager that no-one on this project right now on Windows, so it might be good to get this documented properly.

**Comment by CGMossa** [comment] 2020-08-20 10:53
I've gotten somewhere. 

1. First, I had to build R on Windows. Following this [`r-base` repository has instructions](https://github.com/r-windows/r-base#readme), i.e. have MikTex & Rtools40  installed. 
1.  Reading from the [R Installation and administration; standalone rmath library](https://cran.r-project.org/doc/manuals/r-release/R-admin.html#The-standalone-Rmath-library), I see that if `make install` is enabled, then the `pkg-config` is setup.
I tried to run `make install` and it didn't work. Reading further, it says to run `make -f Makefile.win`. This propagates a whole bunch of files and creates `.dll` and an `.a` file. 
1. Running the `./quick-build.sh` makes it so the instructions:
> (cd ../../gnuwin32; make MkRules)
> (cd ../../include; make -f Makefile.win config.h Rconfig.h Rmath.h)
redundant
1. So this has created one's own `R-devel` within the newly created clone of `r-base` and that contains R with other stuff. The Rmath lib is then located in `r-base/R-devel/src/nmath/standalone`. 
1. Where do I put that? I'll attempt to jam it directly into the `build.rs` for `libR-sys` as I am assuming that this is the binding. And see what happens.

Also, does anyone know why a unix-like command like `make install` didn't just work? One may use pkg-config irregardless if one is on Windows or not.

**Comment by andy-thomason** [comment] 2020-08-20 15:05
Thanks for being a pioneer, here. Windows is a missing link so far.

We could try to make a smoother install through one of the
windows-orientated CI
services such as AppVeyor.

I'll take a look at how some other binding libraries solve the windows
issue.

Andy.

**Comment by dasmoth** [comment] 2020-08-20 20:09
Also not well, equipped to Windows testing (I did quickly try running Windows R on Linux under Wine -- which could make life somewhat easier -- but while it installs fine it hung when starting a session).

@CGMossa: does the R-devel tree you build include a `libR.pc` file anywhere?  If so, put the directory containing this on your `PKG_CONFIG_PATH` and the `libR-sys` build _should_ (famous last words...) pick up your R libraries from there.

If doing your own Windows build doesn't make sure a file, I'd suggest trying to make one by hand for a stopgap, then we can think how best to automate after confirming that works.  For reference, the `libR.pc` file on my Linux machine looks like:

```
rhome=/usr/lib64/R
rlibdir=${rhome}/lib
rincludedir=/usr/include/R

Name: libR
Description: R as a library
Version: 4.0.2
Libs: -Wl,--export-dynamic -fopenmp  -Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -L${rlibdir} -lR
Cflags: -I${rincludedir} -I${rincludedir}
Libs.private:
```

Obviously, the paths will change under Windows and you might want to look at the compiler flags (the `-specs` bit is obviously Redhat-specific, just remove that), but hopefully this gives the general idea...

**Comment by andy-thomason** [comment] 2020-11-10 13:52
I've merged a PR that may make the hello example build on windows and mac. Please can you test it.

**Comment by CGMossa** [comment] 2020-11-10 14:59
I tried it, and things happened, but I got a crash due to a lack of having pkg-config or something similar... 

<details>
```
Welcome to Nushell 0.21.0 (type 'help' for more info)
C:\Users\tpb398\Documents\GitHub\extendr\extendr-api\examples\R\hello(master)> R CMD INSTALL .
* installing to library 'C:/Users/tpb398/Documents/R/win-library/4.0'
* installing *source* package 'hello' ...
** using staged installation
** libs

*** arch - i386
rm -Rf hello.dll ../target/i686-pc-windows-gnu/release/hello.lib empty.o ../target
"C:/rtools40/mingw32/bin/"gcc  -I"C:/R/R-4.0.2/include" -DNDEBUG          -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign -c empty.c -o empty.o
cargo build --target=i686-pc-windows-gnu --release --manifest-path=../Cargo.toml
    Updating crates.io index
  Downloaded cc v1.0.62
  Downloaded 1 crate (52.6 KB) in 1.91s
   Compiling winapi v0.3.9
   Compiling memchr v2.3.4
   Compiling proc-macro2 v1.0.24
   Compiling autocfg v1.0.1
   Compiling glob v0.3.0
   Compiling unicode-xid v0.2.1
   Compiling cc v1.0.62
   Compiling libc v0.2.80
   Compiling version_check v0.9.2
   Compiling bitflags v1.2.1
   Compiling lazy_static v1.4.0
   Compiling log v0.4.11
   Compiling regex-syntax v0.6.21
   Compiling quick-error v1.2.3
   Compiling unicode-width v0.1.8
   Compiling cfg-if v0.1.10
   Compiling vec_map v0.8.2
   Compiling bindgen v0.53.3
   Compiling strsim v0.8.0
   Compiling lazycell v1.3.0
   Compiling rustc-hash v1.1.0
   Compiling peeking_take_while v0.1.2
   Compiling shlex v0.1.1
   Compiling pkg-config v0.3.19
   Compiling syn v1.0.48
   Compiling rawpointer v0.2.1
   Compiling ndarray v0.13.1
   Compiling extendr-api v0.1.3 (C:\Users\tpb398\Documents\GitHub\extendr\extendr-api)
   Compiling num-traits v0.2.14
   Compiling num-integer v0.1.44
   Compiling num-complex v0.2.4
   Compiling clang-sys v0.29.3
   Compiling thread_local v1.0.1
   Compiling nom v5.1.2
   Compiling humantime v1.3.0
   Compiling textwrap v0.11.0
   Compiling libloading v0.5.2
   Compiling matrixmultiply v0.2.3
   Compiling aho-corasick v0.7.15
   Compiling quote v1.0.7
   Compiling which v3.1.1
   Compiling regex v1.4.2
   Compiling winapi-util v0.1.5
   Compiling atty v0.2.14
   Compiling cexpr v0.4.0
   Compiling clap v2.33.3
   Compiling termcolor v1.1.0
   Compiling env_logger v0.7.1
   Compiling extendr-macros v0.1.2 (C:\Users\tpb398\Documents\GitHub\extendr\extendr-macros)
   Compiling libR-sys v0.1.8
error: failed to run custom build command for `libR-sys v0.1.8`

Caused by:
  process didn't exit successfully: `C:/cargo_target_dir\release\build\libR-sys-23c074e90ef7a298\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-env-changed=LIBR_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_ALLOW_CROSS_i686-pc-windows-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_ALLOW_CROSS_i686_pc_windows_gnu
  cargo:rerun-if-env-changed=TARGET_PKG_CONFIG_ALLOW_CROSS
  cargo:rerun-if-env-changed=PKG_CONFIG_ALLOW_CROSS
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=LIBR_STATIC
  cargo:rerun-if-env-changed=LIBR_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_i686-pc-windows-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_i686_pc_windows_gnu
  cargo:rerun-if-env-changed=TARGET_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_i686-pc-windows-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_i686_pc_windows_gnu
  cargo:rerun-if-env-changed=TARGET_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_i686-pc-windows-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_i686_pc_windows_gnu
  cargo:rerun-if-env-changed=TARGET_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR

  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Failure { command: "\"pkg-config\" \"--libs\" \"--cflags\" \"libR\"", output: Output { status: ExitStatus(ExitStatus(1)), stdout: "", stderr: "Package libR
was not found in the pkg-config search path.\r\nPerhaps you should add the directory containing `libR.pc\'\r\nto the PKG_CONFIG_PATH environment variable\r\nNo package \'libR\' found\r\n" } }', C:\Users\tpb398\.cargo\registry\src\github.com-1ecc6299db9ec823\libR-sys-0.1.8\build.rs:38:51
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
make: *** [Makevars.win:11: ../target/-pc-windows-gnu/release/hello.lib] Error 101
ERROR: compilation failed for package 'hello'
* removing 'C:/Users/tpb398/Documents/R/win-library/4.0/hello'
C:\Users\tpb398\Documents\GitHub\extendr\extendr-api\examples\R\hello(master)>
```
</details>

**Comment by CGMossa** [comment] 2020-11-12 14:10
So! With that out of the way (refering to the `libR-sys` stuff), I can actually try this out again.

It compiles, but there is something not working properly. 
The package builds, but the call to `hello` function crashes.

```r
# redacted my startup stuff
> library(hello)
> hello::hello()
Error in .Call("wrap__hello") : 
  "wrap__hello" not resolved from current namespace (hello)
>
```

See this:  
<details>

```
==> Rcmd.exe INSTALL --no-multiarch --with-keep.source hello

* installing to library 'C:/Users/tpb398/Documents/R/win-library/4.0'
* installing *source* package 'hello' ...
** using staged installation
** libs
rm -Rf hello.dll ../target/x86_64-pc-windows-gnu/release/hello.lib empty.o ../target
"C:/rtools40/mingw64/bin/"gcc  -I"C:/R/R-40~1.2/include" -DNDEBUG          -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign -c empty.c -o empty.o
cargo build --target=x86_64-pc-windows-gnu --release --manifest-path=../Cargo.toml
C:/rtools40/mingw64/bin/gcc -shared -s -static-libgcc -o hello.dll tmp.def empty.o -L../target/x86_64-pc-windows-gnu/release -lhello -lws2_32 -ladvapi32 -luserenv -LC:/R/R-40~1.2/bin/x64 -lR
No man pages found in package  'hello' 
   Compiling winapi-x86_64-pc-windows-gnu v0.4.0
   Compiling winapi v0.3.9
   Compiling memchr v2.3.4
   Compiling autocfg v1.0.1
   Compiling proc-macro2 v1.0.24
   Compiling glob v0.3.0
   Compiling unicode-xid v0.2.1
   Compiling libc v0.2.80
   Compiling version_check v0.9.2
   Compiling cc v1.0.62
   Compiling bitflags v1.2.1
   Compiling log v0.4.11
   Compiling lazy_static v1.4.0
   Compiling unicode-width v0.1.8
   Compiling cfg-if v0.1.10
   Compiling quick-error v1.2.3
   Compiling regex-syntax v0.6.21
   Compiling vec_map v0.8.2
   Compiling bindgen v0.53.3
   Compiling strsim v0.8.0
   Compiling lazycell v1.3.0
   Compiling shlex v0.1.1
   Compiling rustc-hash v1.1.0
   Compiling peeking_take_while v0.1.2
   Compiling syn v1.0.48
   Compiling rawpointer v0.2.1
   Compiling ndarray v0.13.1
   Compiling extendr-api v0.1.3 (C:\Users\tpb398\Documents\GitHub\extendr\extendr-api)
   Compiling num-traits v0.2.14
   Compiling num-integer v0.1.44
   Compiling num-complex v0.2.4
   Compiling clang-sys v0.29.3
   Compiling thread_local v1.0.1
   Compiling nom v5.1.2
   Compiling textwrap v0.11.0
   Compiling humantime v1.3.0
   Compiling matrixmultiply v0.2.3
   Compiling libloading v0.5.2
   Compiling aho-corasick v0.7.15
   Compiling quote v1.0.7
   Compiling which v3.1.1
   Compiling regex v1.4.2
   Compiling cexpr v0.4.0
   Compiling atty v0.2.14
   Compiling winapi-util v0.1.5
   Compiling clap v2.33.3
   Compiling termcolor v1.1.0
   Compiling env_logger v0.7.1
   Compiling extendr-macros v0.1.2 (C:\Users\tpb398\Documents\GitHub\extendr\extendr-macros)
   Compiling libR-sys v0.1.9 (C:\Users\tpb398\Documents\GitHub\libR-sys)
   Compiling hello v0.1.0 (C:\Users\tpb398\Documents\GitHub\extendr\extendr-api\examples\R\hello)
    Finished release [optimized] target(s) in 30.64s
C:\rtools40\mingw64\bin\nm.exe: '../target/x86_64-pc-windows-gnu/release/hello.lib': No such file
installing to C:/Users/tpb398/Documents/R/win-library/4.0/00LOCK-hello/00new/hello/libs/x64
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (hello)
```
</details>

**Comment by dasmoth** [comment] 2020-11-12 14:14
@CGMossa: your issue is probably the same thing we've seen on Macs and at least some Linux systems, where the linked tries to be a bit too clever and doesn't include the compiled Rust code in the final library file.  See also, the most recent comments on #19 .  If you add a little bit of C code to empty.c which references the symbol(s) exported from the Rust code, that fixes the problem on Macs -- suspect it may help on Windows too.

**Comment by CGMossa** [comment] 2020-11-12 14:47
That's.. I think that's an issue for someone else to dig into.

I'm standing by now. :D

**Comment by Ilia-Kosenkov** [comment] 2020-11-26 21:35
Hi, just found this project, looks really promising, however, I immediately ran into the Windows package building problem.
In fact, I even had issues building `hello` example in the WSL and had to configure additional environment variables.
The root cause is the `libR-sys` for me, which depends on `llvm`/`clang`, and failed both in Windows and WSL during my first attempts. While I managed to install all dependencies in WSL (Ubuntu), for Windows things look very bad. The crate [docs](https://docs.rs/crate/libR-sys/0.1.10) give some instructions on how to configure the Windows environment, which involves installing `msys2` and bringing in dependencies. From my limited experience, whenever `msys2` is involved, the build process is a complete mess. Currently, I am attempting to follow the instructions and configure `msys2`, which requires around gigabyte or so of downloaded packages and several gigabytes of disk space -- which does not look that exciting for a potential consumer (especially compared to, say, `Rcpp`, which works decently via `rtools` and with minimum configuration).

I am also concerned about the amount of `Rust` dependencies building with the package -- eighty-something as of my last attempt, with troublesome `libR-sys` among it. Even if the package achieves seamless integration of `Rust` code into `R` packages, the package building experience is still an important part of the library usage and should be considered.

**Comment by CGMossa** [comment] 2020-11-26 21:46
We are actually actively refining and looking at this. For instance, I've tried configuring this solely based on rtools, but rtools doesn't have clang.

If you're a little patient, I think soon we'll have these wrinkles ironed out. I ask you to please open issues when you have them, and write what your issue is, and so we can tackle these problems one at a time

**Comment by Ilia-Kosenkov** [comment] 2020-11-26 22:07
@CGMossa, I am sorry, I got too excited about this project and did not intend to ruin the discussion. I will stay on topic.

**Comment by clauswilke** [comment] 2020-11-26 23:33
Also, `libR-sys` is the core of the entire project, if we remove it we have nothing. There are ways in which installation can be made easier in the future, but we're not there yet. First the project needs to reach the stage where all the features for a minimally viable product work in principle.

**Comment by Ilia-Kosenkov** [comment] 2020-11-28 02:26
> 
> 
> So! With that out of the way (refering to the `libR-sys` stuff), I can actually try this out again.
> 
> It compiles, but there is something not working properly.
> The package builds, but the call to `hello` function crashes.
> 
> ```r
> # redacted my startup stuff
> > library(hello)
> > hello::hello()
> Error in .Call("wrap__hello") : 
>   "wrap__hello" not resolved from current namespace (hello)
> >
> ```
> 
> See this:


@CGMossa ,
I may have found the problem, as I managed to build hello sample and successfully run `hello::hello()`.
My rust toolchain produces a `libhello.a` intermediate lib instead of `hello.lib` declared in `Makevars.win`.
As a result, when compiled, `src` folder contains `hello.so` with all the code and `hello.dll` with no exports, which is then called from `R` - obviously to no result as your error message says. Due to the different names, the linker fails to include rust code into the final dll. It can be solved by modifying `Makevars.win`.
Bellow is the output of 
``` $(git diff ; R.exe CMD INSTALL . --no-multiarch  ; Rscript.exe -e "hello::hello()") *>&1  > ../dump.txt                    ```
<details>
<summary>dump.txt</summary>

```

diff --git a/extendr-api/examples/R/hello/src/Makevars.win b/extendr-api/examples/R/hello/src/Makevars.win
index ba233e92..7e45fad5 100644
--- a/extendr-api/examples/R/hello/src/Makevars.win
+++ b/extendr-api/examples/R/hello/src/Makevars.win
@@ -1,6 +1,6 @@
 TARGET = $(subst 64,x86_64,$(subst 32,i686,$(WIN)))-pc-windows-gnu
 LIBDIR = ../target/$(TARGET)/release
-STATLIB = $(LIBDIR)/hello.lib
+STATLIB = $(LIBDIR)/libhello.a
 PKG_LIBS = -L$(LIBDIR) -lhello -lws2_32 -ladvapi32 -luserenv
 
 all: clean
* installing to library 'C:/Users/[redacted]/Documents/R/win-library/4.0'
* installing *source* package 'hello' ...
** using staged installation
** libs
rm -Rf hello.dll ../target/x86_64-pc-windows-gnu/release/libhello.a entrypoint.o ../target
"C:/rtools40/mingw64/bin/"gcc  -I"C:/PROGRA~1/R/R-40~1.3/include" -DNDEBUG          -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign -c entrypoint.c -o entrypoint.o
cargo build --target=x86_64-pc-windows-gnu --release --manifest-path=../Cargo.toml
   Compiling winapi v0.3.9
   Compiling memchr v2.3.4
   Compiling proc-macro2 v1.0.24
   Compiling autocfg v1.0.1
   Compiling unicode-xid v0.2.1
   Compiling cc v1.0.65
   Compiling libc v0.2.80
   Compiling version_check v0.9.2
   Compiling glob v0.3.0
   Compiling log v0.4.11
   Compiling bitflags v1.2.1
   Compiling lazy_static v1.4.0
   Compiling cfg-if v0.1.10
   Compiling regex-syntax v0.6.21
   Compiling unicode-width v0.1.8
   Compiling quick-error v1.2.3
   Compiling vec_map v0.8.2
   Compiling bindgen v0.53.3
   Compiling strsim v0.8.0
   Compiling rustc-hash v1.1.0
   Compiling peeking_take_while v0.1.2
   Compiling shlex v0.1.1
   Compiling lazycell v1.3.0
   Compiling syn v1.0.51
   Compiling ndarray v0.13.1
   Compiling rawpointer v0.2.1
   Compiling extendr-api v0.1.10 (C:\Users\[redacted]\OneDrive\Development\Playground\extendr\extendr-api)
   Compiling num-traits v0.2.14
   Compiling num-complex v0.2.4
   Compiling num-integer v0.1.44
   Compiling nom v5.1.2
   Compiling thread_local v1.0.1
   Compiling clang-sys v0.29.3
   Compiling textwrap v0.11.0
   Compiling humantime v1.3.0
   Compiling matrixmultiply v0.2.3
   Compiling libloading v0.5.2
   Compiling aho-corasick v0.7.15
   Compiling quote v1.0.7
   Compiling which v3.1.1
   Compiling regex v1.4.2
   Compiling atty v0.2.14
   Compiling winapi-util v0.1.5
   Compiling cexpr v0.4.0
   Compiling clap v2.33.3
   Compiling termcolor v1.1.2
   Compiling env_logger v0.7.1
   Compiling extendr-macros v0.1.10 (C:\Users\[redacted]\OneDrive\Development\Playground\extendr\extendr-macros)
   Compiling libR-sys v0.1.10
   Compiling hello v0.1.0 (C:\Users\[redacted]\OneDrive\Development\Playground\extendr\extendr-api\examples\R\hello)
    Finished release [optimized] target(s) in 1m 18s
C:/rtools40/mingw64/bin/gcc -shared -s -static-libgcc -o hello.dll tmp.def entrypoint.o -L../target/x86_64-pc-windows-gnu/release -lhello -lws2_32 -ladvapi32 -luserenv -LC:/PROGRA~1/R/R-40~1.3/bin/x64 -lR
installing to C:/Users/[redacted]/Documents/R/win-library/4.0/00LOCK-hello/00new/hello/libs/x64
** R
** byte-compile and prepare package for lazy loading
** help
No man pages found in package  'hello' 
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (hello)
[1] "hello"
```

</details>

**Comment by yutannihilation** [comment] 2020-11-28 02:33
> My rust toolchain produces a `libhello.a` intermediate lib instead of `hello.lib` declared in `Makevars.win`.

Yes, the latest Rust toolchain generates `.a` for Windows, which many developers don't notice yet.

c.f. https://github.com/r-rust/hellorust/pull/9

**Comment by CGMossa** [comment] 2020-11-28 05:26
Thanks @Ilia-Kosenkov. I think this is a lesson we are relearning constantly. @clauswilke is currently attempting to make an example work, that would also pass `R CMD check`. 

If you want to be on the bleeding edge of this, we have a discord that you could join.

**Comment by clauswilke** [comment] 2020-12-10 07:30
Closing this, as compiling on Windows mostly works now. For remaining problems please file new issues. For problems with libR-sys, please file issues in that repo, not here.

**Closed by clauswilke** 2020-12-10 07:30 UTC
